Default: &defaults
  database: ppl.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ppl_test.sqlite3
  <<: *defaults

Staging:
  database: ppl_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ppl_production.sqlite3
  poolsize: 100
  <<: *defaults
